=== frantergh/2DAM/Accés a dades(Maite)/UD02/NetbeansProjects/Practica1 Leer BookStore/UD02-P1Practica1LeerBookstore/bookstore.dtd
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, authors, price)>
<!ATTLIST book
          cathegory CDATA #REQUIRED
          cover CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
          lang CDATA #REQUIRED>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== frantergh/2DAM/Accés a dades(Maite)/UD02/NetbeansProjects/Practica1 Leer BookStore/UD02-P1Practica1LeerBookstore/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "bookstore.dtd">
<bookstore>
    <book category="children">
        <title lang="en">Harry Potter</title>
        <authors>
            <author>J K. Rowling</author>
        </authors>
        <price>29</price>
    </book>
    <book category="web">
        <title lang="en">XQuery Kick Start</title>
        <authors>
            <author>James McGovern</author>
            <author>Per Bothner</author>
            <author>Kurt Cagle</author>
            <author>James Linn</author>
            <author>Vaidyanathan Nagarajan</author>
        </authors>
        <price>49.99</price>
    </book>
    <book category="cooking">
        <title lang="en">Everyday Italian</title>
        <authors>
            <author>Giada De Laurentiis</author>
        </authors>
        <price>30.00</price>
    </book>
    <book category="web" cover="paperback">
        <title lang="en">Learning XML</title>
        <authors>
            <author>Erik T. Ray</author>
        </authors>
        <price>39.95</price>
    </book>
</bookstore>
